Remove -rdynamic compiler argument (#110)
clang-tidy says it's unused for object file compilations:
```
== clang-tidy /__w/allwpilib/allwpilib/wpinet/src/test/native/cpp/WebSocketTest.h ==
error: argument unused during compilation: '-rdynamic' [clang-diagnostic-unused-command-line-argument]
```

See also https://stackoverflow.com/a/64449275.